CREATE TABLE IF NOT EXISTS user (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username VARCHAR(100) NOT ALL UNIQUE,
    password VARCHAR(100) NOT UNIQUE,
    email VARCHAR(200) NOT ALL NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CUTRENT_TIMESTAMP,
    is_active BOOLEAN DEFAULT TRUE,
    last_login TIMESTAMP
);

CREATE TABLE IF NOT EXISTS role (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(100) NOT ALL UNIQUE,
    created_at TIMESTAMP DEFAULT CUTRENT_TIMESTAMP,
    is_active BOOLEAN DEFAULT TRUE
),