Profiles:
    TwoOrgsOrdererGenesis:
        Orderer:
            Addresses:
                - localhost:7050
            BatchTimeout: 2s
            BatchSize:
                MaxMessageCount: 10
                AbsoluteMaxBytes: 98 MB
                PreferredMaxBytes: 512 KB
            # Kafka:
            #     ReplicationFactor: 1
            #     Broker: localhost:9092
            Policies:
                Readers:
                    Type: Signature
                    Rule: "OR('Org1MSP.member', 'Org2MSP.member')"
                Writers:
                    Type: Signature
                    Rule: "OR('Org1MSP.member', 'Org2MSP.member')"
                Admins:
                    Type: Signature
                    Rule: "OR('Org1MSP.admin', 'Org2MSP.admin')"
        Consortiums:
            SampleConsortium:
                Organizations:
                    - Name: Org1MSP
                      ID: Org1MSP
                      Policies:
                        Admins:
                          Type: Signature
                          Rule: "OR('Org1MSP.admin')"
                    - Name: Org2MSP
                      ID: Org2MSP
                      Policies:
                        Admins:
                          Type: Signature
                          Rule: "OR('Org2MSP.admin')"

    TwoOrgsChannel:
        Consortium: SampleConsortium
        Application:
            Organizations:
                - Name: Org1MSP
                  ID: Org1MSP
                  MSPDir: /home/anand/BC/cloud-federation-network/organizations/peerOrganizations/org1.example.com/msp
                  Policies:
                    Readers:
                      Type: Signature
                      Rule: "OR('Org1MSP.member')"
                    Writers:
                      Type: Signature
                      Rule: "OR('Org1MSP.member')"
                    Admins:
                      Type: Signature
                      Rule: "OR('Org1MSP.admin')"
                - Name: Org2MSP
                  ID: Org2MSP
                  MSPDir: /home/anand/BC/cloud-federation-network/organizations/peerOrganizations/org2.example.com/msp
                  Policies:
                    Readers:
                      Type: Signature
                      Rule: "OR('Org2MSP.member')"
                    Writers:
                      Type: Signature
                      Rule: "OR('Org2MSP.member')"
                    Admins:
                      Type: Signature
                      Rule: "OR('Org2MSP.admin')"
