############################################################
#   CONFIGTX.YAML for Two-Orgs Fabric Network
############################################################

Organizations:

  - &OrdererOrg
    Name: OrdererMSP
    ID: OrdererMSP
    MSPDir: ../organizations/ordererOrganizations/example.com/orderers/orderer.example.com/msp
    Policies:
      Readers:
        Type: ImplicitMeta
        Rule: "ANY Readers"
      Writers:
        Type: ImplicitMeta
        Rule: "ANY Writers"
      Admins:
        Type: ImplicitMeta
        Rule: "MAJORITY Admins"
      BlockValidation:
        Type: ImplicitMeta
        Rule: "ANY Writers"

  - &Org1MSP
    Name: Org1MSP
    ID: Org1MSP
    MSPDir: ../organizations/peerOrganizations/org1.example.com/msp
    AnchorPeers:
      - Host: peer0.org1.example.com
        Port: 7051
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('Org1MSP.admin','Org1MSP.peer','Org1MSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('Org1MSP.admin','Org1MSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('Org1MSP.admin')"

  - &Org2MSP
    Name: Org2MSP
    ID: Org2MSP
    MSPDir: ../organizations/peerOrganizations/org2.example.com/msp
    AnchorPeers:
      - Host: peer0.org2.example.com
        Port: 9051
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('Org2MSP.admin','Org2MSP.peer','Org2MSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('Org2MSP.admin','Org2MSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('Org2MSP.admin')"

############################################################
#  SECTION: Orderer
############################################################
Orderer: &OrdererDefaults
  OrdererType: solo
  Addresses:
    - orderer.example.com:7050
  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 99 MB
    PreferredMaxBytes: 512 KB
  Organizations:
    - *OrdererOrg
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    BlockValidation:
      Type: ImplicitMeta
      Rule: "ANY Writers"

############################################################
#  SECTION: Channel (defaults for all channels)
############################################################
Channel: &ChannelDefaults
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"

############################################################
#  SECTION: Profiles
############################################################
Profiles:

  TwoOrgsOrdererGenesis:
    Orderer:
      <<: *OrdererDefaults
    Consortiums:
      TwoOrgsConsortium:
        Organizations:
          - *Org1MSP
          - *Org2MSP

  TwoOrgsChannel:
    Consortium: TwoOrgsConsortium
    Application:
      Organizations:
        - *Org1MSP
        - *Org2MSP
      Policies:
        Readers:
          Type: ImplicitMeta
          Rule: "ANY Readers"
        Writers:
          Type: ImplicitMeta
          Rule: "ANY Writers"
        Admins:
          Type: ImplicitMeta
          Rule: "MAJORITY Admins"
